baseURL = 'https://nakulbhat.github.io/'
theme = "HugoTex"
title = 'The .aux Archive'

DefaultContentLanguage = "en"
languageCode = 'en-us'

enableInlineShortcodes = true


[pagination]
  pagerSize = 3

[Params.author]
  name = "Nakul Bhat"
  abstract = """During the compilation of a document, LaTeX produces several .aux files containing the content of a document being typeset.
This website is written along similar lines, showcasing some my works-in-progress.
I study [link](google.com)"""

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "paraiso-dark"
[Params]
  lightmode = true
