baseURL = 'https://nakulbhat.github.io/'
theme = "HugoTeX-Plus"
title = 'The Aux Archive'

DefaultContentLanguage = "en"
languageCode = 'en-us'

enableInlineShortcodes = true

[pagination]
  pagerSize = 3

[Params.Author]
  name = "Nakul Bhat"

[Params]
  logo = "/logo.svg"
  htmlTitle = "Nakul Bhat's Portfolio"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    noClasses = false
    guessSyntax = true
    lineNos = false          # true if you want line numbers

[module]
  [module.imports]
    path = "github.com/hugo-mods/lazyimg"
