baseURL = 'https://nakulbhat.github.io/'
theme = "HugoTeX-Plus"
title = 'The aux Archive'

DefaultContentLanguage = "en"
languageCode = 'en-us'

enableInlineShortcodes = true

[pagination]
  pagerSize = 3

[Params]
  htmlTitle = "Nakul Bhat's Portfolio"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "paraiso-dark"

[module]
  [module.imports]
    path = "github.com/hugo-mods/lazyimg"
