baseURL = 'https://nakulbhat.github.io/'
theme = "HugoTeX-Plus"
title = 'The aux Archive'

DefaultContentLanguage = "en"
languageCode = 'en-us'

enableInlineShortcodes = true


[pagination]
  pagerSize = 3

[Params.author]
  name = "Nakul Bhat"
  secondLine = "Academic Portfolio"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "paraiso-dark"
[Params]
  htmlTitle = "Nakul Bhat's Portfolio"
  # lightmode = true
